version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:1818
    ports:
      - "80:8080"
    environment:
      - VITE_API_URL=http://localhost:1818