version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1818:1818"
    depends_on:
      - mongo
      - redis_cache
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DATABASE_NAME=demo
      - REDISREAD_URI=redis://redis_cache:6379
      - REDIS_URI=redis://redis_cache:6379
      - PORT=1818
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db
  redis_cache:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379

volumes:
  mongo_data:
  redis_volume_data:
