version: '3.8'
services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongo
  #   environment:
  #     - MONGODB_URI=mongodb://localhost:27017
  #     - DATABASE_NAME=demo
        # - REDISREAD_URI=redis://localhost:6379
        # - REDIS_URI=redis://localhost:6379

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db
  redis_cache:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379

volumes:
  mongo_data:
  redis_volume_data:
