version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1818:1818"
    depends_on:
      - mongo
      - redis_cache
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DATABASE_NAME=demo
      - REDISREAD_URI=redis://garnet:6379
      - REDIS_URI=redis://garnet:6379
      - PORT=1818

volumes:
  mongo_data:
  redis_volume_data:
