openapi: 3.1.0
info:
  title: API task_management_system backend service
  version: "1.0"
servers:
  - url: /api/user
  - url: /api/task
paths:
  /get_all:
    get:
      tags:
        - Task
      description: Get all task
      # security:
      #   - bearerAuth: []
      summary: Get all task
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
              message: Get All Task Success
              data:
                - task_id: task-nbAU
                  name: ซื้อของเข้าบ้าน
                  details: "ไปซูเปอร์มาร์เก็ตเพื่อซื้อของจำเป็น"
                  status: "ทำอยู่"
  /add_task:
    post:
      tags:
        - Task
      summary: Add task
      requestBody:
        required: true
        description: Add task payload
        content:
          application/json:
            example:
              name: อ่านหนังสือ
              details: อ่านหนังสือเรื่องการพัฒนาตนเอง 30 นาที
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                message: "Add New Task Success"
  /edit_task/{task_id}:
    put:
      tags:
        - Task
      description: Update task
      summary: Update task
      parameters:
        - in: query
          name: task_id
          schema:
            type: string
          value: task-R8Ih
          required: true
      requestBody:
        required: true
        content:
          application/json:
            examples:
              example_1:
                value:
                  name: tset12
                  details: "12"
                  status: "ทำอยู่"

      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                message: Edit Task Success

  /delete_task/{task_id}:
    delete:
      tags:
        - Task
      description: Delete task
      summary: Delete task
      parameters:
        - in: query
          name: task_id
          schema:
            type: string
          value: task-R8Ih
          required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                message: Delete Task Success
  /register:
    post:
      tags:
        - User
      description: Register user
      summary: Register user
      requestBody:
        required: true
        content:
          application/json:
            example:
              username: tset12
              password: "12"
              password_confirm: "12"
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                message: "Register User Success"

  /login:
    post:
      tags:
        - User
      description: Login
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            example:
              username: tset12
              password: "12"
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                message: Login User Success
                data: "JWT token"
  /get_profile:
    get:
      tags:
        - User
      description: Get profile user
      summary: Get profile user
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                message: "Get Profile Success"
                data:
                  user_id: e4ca13bb-c1e7-4354-862-sdasd
                  username: tset12
        "401":
          description: Unauthorized
          content:
            application/json:
              example:
                message: "Unauthorization Token."

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Authorization header using the Bearer scheme.
      in: header
      name: Authorization

tags:
  - name: User
    description: User All endpoint
  - name: Task
    description: Task All endpoint
